/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _COOKIE_H_RPCGEN
#define _COOKIE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct args {
	int *cookiecount;
	char *name;
};
typedef struct args args;

#define COOKIE_PRG 28855
#define COOKIE_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define getmemygookie 1
extern  int * getmemygookie_1(args *, CLIENT *);
extern  int * getmemygookie_1_svc(args *, struct svc_req *);
extern int cookie_prg_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define getmemygookie 1
extern  int * getmemygookie_1();
extern  int * getmemygookie_1_svc();
extern int cookie_prg_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_args (XDR *, args*);

#else /* K&R C */
extern bool_t xdr_args ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_COOKIE_H_RPCGEN */
