/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "cookie.h"

bool_t
xdr_args (XDR *xdrs, args *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->cookiecount))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->name, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
