/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _COOKIE_H_RPCGEN
#define _COOKIE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define COOKIE_PRG 22855
#define COOKIE_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define GETMEMYCOOKIE 1
extern  int * getmemycookie_1(char **, CLIENT *);
extern  int * getmemycookie_1_svc(char **, struct svc_req *);
extern int cookie_prg_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GETMEMYCOOKIE 1
extern  int * getmemycookie_1();
extern  int * getmemycookie_1_svc();
extern int cookie_prg_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_COOKIE_H_RPCGEN */
